<?php

	$cn = [
		////////////////////
		// Global message //
		////////////////////
			//category
		'home_title' => 'DELL服务卡销售和管理系统',
		'home_title_m' => '服务卡',
		'label_overview' => '概览',
		'label_product' => '产品',
		'label_order' => '订单',
		'label_sale' => '销售',
		'label_stock' => '库存',
		'label_statistic' => '统计',
		
		'label_generate' => '生成',
		'label_reward' => '奖励',
		'label_sale_amount' => '销量',
		'label_staff' => '人员',
		'label_user' => '用户',
		'label_client' => '客户',
		'label_person' => '人',
		'label_dealer' => '经销商',
		'label_message' => '系统消息',
		
		'label_added' => '新增',
		'label_total' => '总计',
		'label_cn_cunit' => '元',
		'label_card_unit' => '张',
		//pc add
		'label_log' => '日志',
		'label_back' => '返回',
		
			// date & time
		'day' => '日',
		'qr_code' => '二维码',
		'days' => '天',
		'week' => '周',
		'month' => '月',
		'season' => '季',
		'year' => '年',
		'years' => '年',
		'day_short' => '日',
		'week_short' => '周',
		'month_short' => '月',
		'season_short' => '季',
		'year_short' => '年',
		'start date' => '开始时间',
		'end date' => '截止时间',
		'start day' => '开始日期',
		'end day' => '截止日期',
		'forever_valid_time' => '永久',
		'new' => '新',
		
			// number
		'number_0' => '零',
		'number_1' => '一',
		'number_2' => '二',
		'number_3' => '三',
		'number_4' => '四',
		'number_5' => '五',
		'number_6' => '六',
		'number_7' => '七',
		'number_8' => '八',
		'number_9' => '九',

        // number sequence
        'admin_level_dealer' => 'DELL本店',
        '1st_level_dealer' => '一级经销商',
        '2nd_level_dealer' => '二级经销商',
        '3rd_level_dealer' => '三级经销商',
        '4th_level_dealer' => '四级经销商',
        '5th_level_dealer' => '五级经销商',
        '6th_level_dealer' => '六级经销商',
        '7th_level_dealer' => '七级经销商',
        '8th_level_dealer' => '八级经销商',
        '9th_level_dealer' => '九级经销商',
        '10th_level_dealer' => '十级经销商',
        '11th_level_dealer' => '十一级经销商',
        '12th_level_dealer' => '十二级经销商',
        '13th_level_dealer' => '十三级经销商',
        '14th_level_dealer' => '十四级经销商',
        '15th_level_dealer' => '十五级经销商',
        '16th_level_dealer' => '十六级经销商',
        '17th_level_dealer' => '十七级经销商',
        '18th_level_dealer' => '十八级经销商',
        '19th_level_dealer' => '十九级经销商',
        '20th_level_dealer' => '二十级经销商',

        // general
		'physical_card_code' => '实物卡代码',
		'selected_physical_card' => '选择的实物卡',
		'selected_pcard_quantity' => '所选的牌数量',
		'toselect_pcard_quantity' => '贺卡数量选择',
		'valid_pcard_code' => '有效的实物卡代码',
		'valid_pcard_code_s' => '有效的卡',
		'invalid_pcard_code' => '无效的实物卡代码',
		'card_code_s' => '卡号',
		'import' => '导入',
		'template_file' => '模板文件',
		'template_sample' => '模板示例',
		'error_input_data_incorrect' => '输入值不正确。',
		'error_input_data_duplicate' => '输入值的重复。',
		'error_file_upload_failed' => '文件上传失败。',
		'error_no_valid_card' => '没有有效的卡',
		'login' => '登录',
		'field_required' => '必填项目，必需填一下。',
		'field_required_s' => '必填项目',
		'select' => '选择',
		'setting' => '设置',
		'submit' => '提&nbsp交',
		'purchase' => '进货',
		'search' => '查询',
		'note' => '注',
		'all' => '全部',
		'all city' => '全部地区',
		'unit price' => '单价',
		'quantity' => '数量',
		'discount' => '优惠',
		'purchase date' => '购买时间',
		'seller' => '销售员',
		'revenue' => '实收',
		'register' => '注册',
		'register_short' => '注册',
		'service card' => '服务卡',
		'service card_short' => '服务卡',
		'activation' => '激活',
		'activation_short' => '激活',
		'number' => '号码',
		'id' => '号码',
		'password' => '密码',
		'password_short' => '密码',
		'valid period' => '有效期',
		'client' => '客户',
		'name' => '姓名',
		'phone' => '电话',
		'clientname' => '客户姓名',
		'contact' => '联系方式',
		'download_all' => '全部下载',
		'download' => '下载',
		'download_short' => '下载',
		'return' => '退货',
		'email' => '邮箱地址',
		'email_short' => '邮箱',
		'sales represent' => '销售代表',
		'di' => '第',
		'tiao' => '条',
		'total' => '共',
		'no' => '编号',
		'code' => '代码',
		'define_name' => '名称',
		'complete' => '完成',
		'cancel' => '取消',
		'custom' => '自定义',
		'synchronize' => '同步',
		'synchronize_m' => '同步',
		'type' => '分类',
		'state' => '状态',
		'introduce' => '介绍',
		'introduce_m' => '介绍',
		'activate_card' => '激活服务卡',
		'promotion' => '促销',
		'promotion_m' => '促销',
		'card_no' => '卡号',
		'scan' => '扫描',
		'add' => '添加',
		'ten_pro' => '折',
		'remain' => '剩余',
		'not_have' => '无',
		'all_select' => '全部选择',
		'confirm' => '确定',
		'use_on' => '启用',
		'use_off' => '停用',
		'rule' => '规则',
		'income' => '收入',
		//pc add
		'prompt' => '提示',
		'modify' => '修改',
		'no_data' => '目前该资料不存在。',
		'item_count' => '件',
		'others' => '外',
		'delete_selected' => '批量删除',
		'short_purchase' => '进',
		'short_return' => '退',
		'cost_price' => '成本价格',
		'now_loading' => '正在加载',
		'select_dealer' => '选择经销商',
		'order_approved' => '已审批',
		'order_unapproved' => '未审批',
		'save_dlg_message_fail' => '保存失败, 请再试一次',
		'send_dlg_title' => '发送成功',
		'send_dlg_title_fail' => '发送失败',
		'send_dlg_message_fail' => '发送失败, 请再试一次',
		'import_dlg_title' => '导入成功',
		'import_dlg_message' => '已成功导入了数据文件。',
		'import_dlg_title_fail' => '导入失败',
		'import_dlg_message_fail' => '失败导入了数据文件。',
		'del_confirm_title' => '确认删除',
		'del_confirm_message' => '您确定要删除所选项目吗？<br>一旦删除的项目无法恢复。',
		'select_confirm_title' => '确认选择',
		'select_confirm_message' => '请选择一个或多个项目',
		'newmsg_confirm_title' => '新信息到了',
		'newmsg_confirm_message' => '个新信息到了。请到信息页面确认。',
		'card_generate' => '卡生成',
		'go_msg_page' => '到信箱',
		'info' => '信息',
		'address' => '地址',
		'dingding_account' => '钉钉账户',
		'corporation' => '总代',
		'level' => '级别',
		'position' => '职位',
		'my_account' => '我的',
		'my_company' => '我的商店',
		'my_account_l' => '我的账号',
		'my_up_dealer' => '上级经销商',
        'unit_price' => '单价',
		
		//Error
		'err_no_permission' => '你没有适当的权限!',
		'please_select' => '请选择项目',
		'no_corresponding_data' => '没有相应的数据！',
		'no_permission_edit' => '没有相应的数据！',
		'err_save_fail' => '存档失败。 请联系管理员！',
		'password_setting' => '密码设置',
		'password_length' => '密码生成长度',
		
		//////////////////
		//   overview   //
		//////////////////
		'ov_period_lavel' => '本:preriod_time数据概览',
		'ov_period_card' => '本:preriod_time服务卡数据',
		'ov_client_cards' => '客户激活',
		'ov_sale_cards' => '销售数量',
		'ov_stock_cards' => '当前库存',
		'ov_soon_expire' => '即将到期',
		'ov_soon_expire_m' => '即将到期',
		'ov_expired' => '已过期',
		'ov_activation' => '激活',
		'ov_register' => '注册',
		'ov_manage_machine_code' => '机器码管理',
		'ov_card_business' => '服务卡业务',
		'ov_manage_card' => '服务卡管理',
		'ov_manage_sales' => '销售管理',
		'ov_today_data' => '今日数据',
		'ov_search_card_data' => '服务卡数据查询',
		'import_machine_code_m' => '导入DELL机器码',
		'list_machine_code_m' => 'DELL机器码',
		'success_machine_code_m' => 'DELL机器码注册成功',
		'exist_machine_code_m' => 'DELL机器码已经存在',
		'fail_machine_code_m' => 'DELL机器码注册失败',
		'scan_machine_code_m' => '扫描DELL机器码',
		'ov_period_week_m' => '本周',
		'ov_period_month_m' => '本月',
		'current_month_m' => '当月',
		'ov_period_season_m' => '本季度',
		'time_quater' => '季度',
		'ov_period_year_m' => '今年',
		'one_year_m' => '一年',
		'ov_period_custom_m' => '自定义',
		'ov_yesterday_gold_sale' => '昨日金牌销售',
		//pc add
		'ov_one_year_products' => '灵越质保一年产品',
		'ov_one_year_services' => 'DELL一年上门服务',
		'ov_product_code' => '产品代码',
		'ov_sales_store' => '销售门店',
		'ov_status' => '状态',
		'ov_details' => '详情',
		'ov_machine_code_management' => '机器码管理',
		'ov_batch_deletion' => '机器码管理',
		'ov_batch_import' => '批量导入',
		'ov_machine_code_number' => '机器码编号',
		'ov_import_time' => '导入时间',
		'ov_bulk_import_machine_code' => '批量导入机器码',
		'ov_select_the_import_file' => '选择导入文件',
		'ov_alarm_msg' => '导入文件请按照模板格式进行填写，点这里<a href="./contents/import/machine_code/sample/machine_template_new.xlsx" class="fontcolorblue">下载模板</a>。',
		'ov_import' => '导入',
		'service_type' => '服务类型',
		
		//////////////////
		//    product   //
		//////////////////
		'pr_label' => '产品',
		'pr_edit_m' => '产品编辑',
		'pr_add_m' => '添加产品',
		'pr_info' => '产品信息',
		'pr_item_manage' => '管理类别',
		'pr_item_add' => '添加产品',
		'pr_item_all' => '全部产品',
		'pr_item_no' => '产品编号',
		'pr_item_name' => '产品名称',
		'pr_item_kind' => '产品分类',
		'pr_item_price' => '产品价格',
		'pr_order_limit' => '订单限制',
		'pr_promotion_price' => '促销价格',
		'pr_item_status' => '产品状态',
		'pr_item_description' => '产品说明',
		'pr_item_stock' => '产品库存',
		'pr_item_edit' => '编辑',
		'pr_item_save' => '保存',
		'pr_item_delete' => '删除',
		'pr_item_cancel' => '取消',
		'pr_item_select_m' => '选择产品',
		'pr_type_manage_title' => '分类管理',
		'pr_type_manage' => '+分类管理',
		'pr_type_add' => '+添加分类',
		'pr_standard_price' => '标准零售价',
		'pr_standard_price_m' => '标准零售价',
		'pr_standard_price_s' => '零售价',
		'pr_enter_card_password' => '输入卡号和密码激活服务',
		'pr_notify_no_price' => '您还没有设置产品价格',
		'pr_notify_set_price?' => '是否现在去设置产品价格？',
		'pr_set_price' => '设置产品价格',
		'pr_not_now' => '暂时不设置',
		'pr_enter_type_name' => '请输入新的分类名称',
        'pr_catalog_level' => '分类等級',
        'pr_catalog_name' => '分类名称',
        'pr_update_date' => '添加日子',

        //pc add
		'pr_list' => '产品列表',
		'pr_all_categories' => '全部产品分类',
		'pr_conventional' => '常规产品',
		'pr_unconventional' => '非常规产品',
		'pr_non-national' => '非国行产品',
		'pr_level2_classification' => '第二级产品分类',
		'pr_class1_classification' => '一级产品分类',
		'pr_class2_classification' => '二级产品分类',
		'pr_class3_classification' => '自定义产品分类',
		'pr_class1_classification_s' => '一级分类',
		'pr_class2_classification_s' => '二级分类',
		'pr_class3_classification_s' => '自定义分类',
		'pr_view' => '查看',
		'pr_return' => '返回',
		'pr_service_card_information' => '服务卡信息',
		'pr_service_card_cover' => '服务卡封面',
		'pr_description' => '产品介绍',
		'pr_extension_card' => '延保卡',
		'pr_home_repair_card' => '上门维修卡',
		'pr_edit_save_msg' => '您编辑的服务卡产品“{?product.name?}”<br>还未设置价格，去设置吗？',
		'pr_setting_price' => '去设置价格',
		'pr_not_set_yet' => '暂不设置',
		'pr_classification_management' => '产品分类管理',
		'pr_type_level' => '产品分类等级',
		'pr_name' => '产品分类名称',		
		'pr_active_status_desciption' => '卡片激活成功的。',
		'pr_active_continue' => '继续注册',
		'pr_no_card' => '没有卡',
		'pr_register_fail' => '注册失败',
		'upload card logo image' => '点击卡券封面更换图片',
		'pr_save_dlg_title' => '保存成功',
		'pr_save_dlg_message' => '产品保存成功',
		'pr_save_dlg_title_fail' => '保存失败',
		'pr_save_dlg_message_fail' => '产品保存失败, 请再试一次',
		'pr_save_dlg_message_exist' => '此产品名称已经存在.',
		
		//////////////////
		//     order    //
		//////////////////
		'od_info' => '订单信息',
		'od_setting' => '订单设置',
		'od_detail' => '订单详情',
		'od_start_order' => '发起订单',
		'od_order_all' => '全部订单',
		'od_order_sales' => '出货单',
		'od_order_ship' => '进货单',
		'od_order_return' => '退换货',
		'od_cards_all' => '全部服务卡产品',
		'od_dealers_all' => '全部经销商',
		'od_type_price' => '折扣价/原价',
		'od_order_quantity' => '下单数量',
		'od_order_date' => '下单时间',
		'od_order_settled' => '结算金额',		
		'od_order_type' => '订单类型',
		'od_prod_select' => '选择产品',
		'od_discount_price' => '折扣价',
		'od_original_price' => '原价',
		'od_quantity' => '订单数量',
		'od_remain_stock' => '剩余库存',
		'od_alert_lessthan' => '本产品下单数量每次不得少于',
		'od_order_now' => '立即下单',
		'od_order_pending' => '待审批',
		'od_order_sold' => '已售出',
		'od_order_returned' => '已退货',
		'od_order_no' => '订单号',
		'od_order_confirm' => '确认订单',
		'od_agree_purchase' => '同意进货',
		'od_agree_return' => '同意退货',
		'od_purchase_total2' => '进货订单总计',
		'od_return_total2' => '退货订单总计',
		'od_is_it_correct' => '确认吗？',
		'od_allow_multiple_purchase' => '允许多种产品批量组合进货',
		'od_minval_single_purchase' => '单产品进货最小数量 （张）',
		//pc add
		'od_search_name' => '请输入名称或代码搜索...',
		'od_export' => '导出待审核表单',
		'od_import' => '导入已审核表单',
		'od_product' => '订单产品',
		'od_status' => '订单状态',
		'od_effective_time' => '订单生效时间',
		'od_return_success_time' => '退货成功时间',
		'od_number' => '订单号码',
		'od_effective_time1' => '生效时间',
		'od_purchase_total' => '进货 总计',
		'od_total_price' => '总价',
		'od_myorder' => '我的订单',
		'od_export_title' => '出口订单',
		'od_import_title' => '进口秩序',
		'od_import_msg' => '导入文件请按照模板格式进行填写',
		'od_export_msg' => '请输入欲发送的邮件。',
		'od_purchased' => '已进货',
		'od_agree_status' => '批准状态',
		'od_agree' => '同意',
		'od_disagree' => '不同意',
		'od_refusal' => '拒绝',
		'od_pcard_import_result' => '文件导入结果',
		'od_pcard_valid_cards' => '有效卡',
		'od_pcard_invalid_cards' => '无效卡',
		'od_pcard_invalid_cards_list' => '无效卡列表',
		'od_pcard_quantity_lack' => '选择的实物卡的数量不够。',
		'od_pcard_quantity_return_lack' => '返回的实物卡列表是不准确的。',
		
		
		//////////////////
		//    sales     //
		//////////////////
		'sl_info' => '订单信息',
		'sl_card_active' => '服务卡激活',
		'sl_unregistered' => '未注册',
		'sl_registered' => '已注册',
		'sl_unlimited' => '未绑定',
		'sl_servicecard_number_search' => '可输入服务卡号码进行查询',
		'sl_seller' => '销售人员',
		'sl_card_product' => '服务卡产品',
		'sl_continue_register' => '继续用户注册',
		'sl_notyet_register' => '暂不注册',
		'sl_binding_card' => '绑定服务卡',
		'sl_machine_code' => '机器设备码',
		'sl_after_sale' => '售后地址',
		'sl_user_register' => '用户注册',
		'sl_register_ranking' => '产品排行',
		'sl_income_ranking' => '收入排行',
		'sl_dealer_ranking' => '经销商排行',
		'sl_seller_ranking' => '销售排行',
		'sl_my_sale_amount' => '我的销量',
		'sl_total_sale_amount' => '总销量',
		'sl_my_income' => '我的收入',
		'sl_sales_total' => '销售总额',
		//pc add
		'sl_product_category' => '产品类别',
		'sl_expired' => '过期',
		'sl_highest_sales' => '销量最高',
		'sl_dealer_name' => '经销商名称',
		'sl_selling_best' => '销量最好产品',
		'sl_salesperson_name' => '销售员名称',
		'sl_owned_stores' => '所属门店',
		'sl_volume' => '销售量',
		
		//////////////////
		//    stock     //
		//////////////////
		'st_info' => '库存信息',
		'st_setting' => '库存设置',
		'st_cardname_search' => '可输入服务卡产品名称进行查询',
		'st_purchase_retail' => '进货价/零售价',
		'st_purchase_channel' => '进货渠道',
		'st_servicecard_operation' => '服务卡操作',
		'st_emailsend_note' => '服务卡及激活密码将发送到您的指定邮箱',
		'st_download_servicecard' => '下载服务卡',
		'st_return_servicecard' => '服务卡退换货',
		'st_return_cardname' => '退货服务卡',
		'st_return_count' => '退货数量',
		'st_return_count_available' => '当前可退数量',
		'st_want_exchange' => '是否换货',
		'st_item_exchange' => '更换产品',
		'st_item_stocknote' => '该产品当前库存',
		'st_submit_application' => '提交申请',
		'st_insufficient_stock' => '库存不足',
		'st_soon_disable' => '即将失效',
		'st_enter_email' => '请输入下载服务卡信息的邮箱',
		'st_purchase_price' => '进价',
		'st_purchase_soon' => '立即进货',
		'st_return_availabe' => '可退',
		'st_return_request' => '申请退货',
		'st_purchase_notify' => '正在进货，总计',
		'st_return_notify' => '正在申请退货，总计',
		'st_stock_shortage_warning' => '库存不足预警提醒',
		'st_stock_shortage_warning_count' => '库存不足时候预警数量（张）',
		'st_stock_expire_warning' => '库存即将失效提醒',
		'st_stock_expire_warning_count' => '库存即将失效提醒天数',
		'st_countdown_after_agree' => '审核通过开始计算',
		//pc add
		'st_search' => '请输入服务卡号搜索...',
		'st_dealer_search' => '请输入经销商名称查询...',
		'st_user_search' => '请输入用户名称查询...',
		'st_physical_card_short' => '实物',
		'st_physical_card' => '实物卡',
		'st_virtual_card_short' => '虚拟',
		'st_virtual_card' => '虚拟卡',
		'st_usabled' => '可使用',
		'st_service_card_information_details' => '服务卡信息详情',
		'st_product_type' => '产品类型',
		'st_machine_code' => '机器码',
		'st_machine_code_s' => '机器码',
		'st_customer_information' => '客户信息',
		'st_username' => '用户姓名',
		'st_notyet_actived' => '未激活',
		'st_already_actived' => '已激活',
		'st_already_saled' => '已售出',
		'st_already_expired' => '已过期',
		'st_mail_send_message' => '产品库存信息发送到{?sendemail?}。请检查您的电子邮件收件箱',
		'st_download_title' => '产品库存信息下载',
		'st_download_toemail' => '发送到邮件',
		'st_download_tofile' => '下载到文件',
		
		//////////////////
		//  Statistics  //
		//////////////////
		'sta_info' => '统计信息',
		'sta_sort_sales' => '按销量排序',
		'sta_sort_purchase' => '按进货排序',
		'sta_sort_shipped' => '按出货量排序',
		'sta_dealer_name' => '经销商名称',
		'sta_purchase_order' => '进货订单',
		'sta_shipment_order' => '出货订单',
		'sta_return_order' => '退换货订单',
		'sta_terminal_order' => '终端销量',
		'sta_sale_agentname' => '销售代表名称',
		'sta_sale_amount' => '销售数量',
		'sta_sale_price' => '销售金额',
		'sta_bonus_price' => '红包奖励',
		'sta_bonus_status' => '奖励情况',
		'sta_sale_point' => '所属经销商',
		'sta_bonus_send' => '发红包奖励',
		
		//////////////////
		//     User     //
		//////////////////
		'u_info' => '用户信息',
		'u_terminal_user' => '终端客户',
		'u_username_search' => '可输入用户名称查询',
		'u_user_name' => '用户名称',
		'u_buy_product' => '购买产品',
		'u_dealer_channel' => '经销商渠道',
		'u_servicecard_id' => '服务卡号',
		'u_servicecard_pass' => '卡密码',
		'expire_date' => '到期时间',
		'person_charge' => '负责人',
		'u_office_address' => '经销商地址',
		'u_office_level' => '经销商级别',
		'u_customer_type' => '客户类型',
		'u_dealer_code' => '经销商代码',
		'u_reg_time' => '注册时间',
		'u_dealer_info' => '经销商信息',
		'u_none_reward' => '未发放奖励',
		'u_give_reward' => '奖励已发放',
		'u_sales_shortfall' => '销售未达标',
		'u_import_userdata' => '即将从钉钉同步销售人员数据',
		'u_btn_import' => '立即同步',
		'u_import_dealerdata' => '即将从服务卡系统同步经销商数据',
		'u_outstanding_price' => '未结算金额',
		'u_settled_month' => '本月已结清',
		'u_item_stock' => '产品库存',
		'u_activation_count' => '激活量',
		'u_register_count' => '注册量',
		'u_total_sales' => '总销售额',
		'u_cur_month_sales' => '本月销量额',
		'u_outstanding_order' => '未结算订单',
		'u_outstanding_writeoff' => '确定核销未结算金额',
		//pc add
		'u_retail_stores' => '零售门店',
		'u_import' => '导入经销商信息',
		'u_monthly_settlement_amount' => '本月结算金额',
		'u_unsettlement' => '未结算',
		'u_settled' => '已结算',
		'u_area' => '所属区域',
		'u_contact_address' => '联系地址',
		'u_bindsigned' => '已绑定钉钉账号',
		'u_product_activation' => '产品激活',
		'u_product_registration' => '产品注册',
		'u_confirm' => '确认已结算',
		'u_level' => '用户等级',
		'u_district' => '所属地区',
		'u_bonus' => '奖励金',
		
		//////////////////
		//    message     //
		//////////////////
		'ms_info' => '系统消息',
		'ms_label_all' => '全部消息',
		'ms_label_notification' => '通知消息',
		'ms_label_inspection' => '审核信息',
		'ms_search_keyword' => '可输入关键字进行查询',
		'ms_delete_message' => '删除消息',
		'ms_message_type' => '消息类型',
		'ms_message_content' => '消息内容',
		'ms_message_time' => '到达时间',
		'ms_message_operation' => '用户操作',
		'ms_details' => '查看详情',
		'ms_purchase_application' => '进货申请',
		'ms_purchase_agree' => '同意进货',
		'ms_refuse_application' => '拒绝申请',
		'ms_oder_prefix_notification' => '您的订单已生效',
		'ms_oder_surfix_notification' => '已进入库存',
		'Close' => '关闭',
		'close' => '关闭',
		'ms_seller_new_prefix' => '您有 ',
		'ms_seller_new_suffix' => '条新消息，请注意查收',
		'ms_tab_all' => '全部通知',
		'ms_tab_system' => '系统通知',
		'ms_tab_audit' => '审核信息',
		'ms_tab_order' => '订单信息',
		
		//////////////////
		//    Price     //
		//////////////////
		'price_label' => '价格',
		'price_pricing' => '定价',
		'price_promotion' => '+促销设置',
		'price_promotion_text' => '促销设置',
		'price_change_price' => '改价',
		'price_discount_price' => '折扣促销',
		'price_discount_product' => '选择折扣产品',
		'price_promotion_period' => '促销有效期',
		'price_purchase_price' => '我的进货价',
		'price_shipment_price' => '我的出货价',
		'price_wholesale_price' => '出货价',
		'price_store_price' => '门店销售价',
		'price_purchase_our' => '我的进货价',
		'price_current_selected' => '当前选择 ',
		'price_item_unit' => '个产品',
		'price_set_discount' => '设置折扣',
		'price_selected_items' => '已选择产品',
		//pc add
        'label_table_image' => '图像',
        'label_table_action' => '操作',
		'price_retail_price' => '零售价',
        'price_promotional_discount' => '促销折扣',
		'price_batch_setting' => '批量设置',
		'price_promotion_time' => '促销时间',
		'price_promotional_outlets' => '促销网点',
		'price_selected_products' => '已选产品',
		'price_custom_settings' => '自定义设置',
		'price_admin_dealer' => 'DELL本店',
		'price_discount_rate' => '折扣率',
		'price_actual_price' => '实际价格',
		'price_change_price' => '更改价格',
		'price_total_promotion' => '总的促销',
		'price_level_dealer' => '级经销商',
		'price_success' => '成功',
		'price_save_fail' => '保存失败!',
		'price_base' => '成本价',
		'price_order_limit' => '订货数量限定',
		'price_seller' => '店员',
		'price_sell' => '售价',
		'price_set_confirm' => '是否确认价格？',
		'price_btn_confirm' => '确认',
		'price_btn_cancel' => '取消',
		'price_set_low_alert' => '“出货价不能低于进货价”是否继续操作？',
		'price_btn_continue' => '继续',
		'price_sending' => '发送中...',
		'price_save_success' => '保存成功!',
		
		
		//////////////////
		//    Register  //
		//////////////////
		'rg_already_act' => '已激活产品',
		'rg_regiset_dell_machine_code' => '注册绑定DELL机器码',
		'rg_scane_m_code' => '扫描机器码',
		'rg_submit' => '提交注册',
		'rg_success_register' => '您已成功完成注册',
		'rg_success_save' => '您已成功完成保存',
		'rg_success_refused' => '操作成功',
		'rg_fail_save' => '您已失败完成保存',
		'rg_fail_refus' => '操作失败',
		'rg_error_save' => '没有注册的机器代码。',
		'rg_sale_price' => '销售价格',
		'rg_invalid_number' => '无效数字',
		'rg_invalid_pass' => '密码不匹配。',
		
		//////////////////
		//    Generate  //
		//////////////////
		'gen_select_card' => '选择服务卡',
		'gen_generate_card_short' => '生成卡',
		'gen_generate_card' => '生成服务卡',
		'gen_card_no_example' => '卡号示例',
		'gen_card_part_id' => '产品ID',
		'gen_card_part_area' => '地区ID',
		'gen_card_part_random' => '随机数字',
		'gen_pwd_example' => '密码示例',
		'gen_btn_generate' => '生&nbsp成',
		'gen_msg_generate' => '正在生成服务卡',
		'gen_physical_card_inventory' => '实物卡库存',
		'gen_virtual_card_inventory' => '虚拟卡库存',
		'gen_dealer_inventory' => '经销商库存',
		'gen_service_card_name' => '服务卡名称',
		'gen_service_card_code' => '服务卡代码',
		'gen_service_card_expiry_date' => '服务卡有效期',
		'gen_select_the_service_card_type' => '选择服务卡类型',
		'gen_mcard_type' => '卡类型',
		'gen_enter_service_cards' => '输入服务卡数量',
		'gen_service_card_rules' => '生成服务卡规则',
		'gen_check_generate' => '确认卡的创建',
		'gen_check_priv' => '已创建了',
		'gen_check_next' => '。',
		'gen_check_count' => '个',
		'gen_check_cardcount' => '信用卡生成过多',
		'gen_invalid_number10000' => '数字值在1到10000之间。',
		
		
		//////////////////
		//    Purchase  //
		//////////////////
		'pur_purchase_price' => '进货价',
		'pur_bulk' => '批量进货',
		'pur_operating' => '操作',
		'pur_price' => '进货单价',
		'pur_btn_msg' => '总计 600000 元，提交进货单',
		'pur_btn_msg_prev' => '总计',
		'pur_btn_msg_next' => '元，提交进货单',
		'pur_check_addtitle' => '采购订单',
		'pur_check_add_prev' => '购买了',
		'pur_check_return_prev' => '已经退回了',
		'pur_check_add_next' => '。',
		'pur_check_add_count' => '张',
		'pur_check_success' => '操作成功。',
		'pur_is_price' => '产品的价格并不存在。',
		'pur_warning' => '价格设定警告!!!',
		'pur_invalid_prev1' => '数字值在',
		'pur_invalid_prev2' => '到',
		'pur_invalid_prev3' => '之间。',
		'pur_continue_work' => '你想继续吗?',
		
		//////////////////
		//    Reward    //
		//////////////////
		'rew_reward_setting' => '奖励设置',
		'rew_reward_setting_btn' => '+奖励设置',
		'rew_reward_unissued' => '未发放',
		'rew_reward_issued' => '已发放',
		'rew_sales_bonus' => '销售奖励',
		'rew_agree_bonus?' => '确认发放吗？',
		'rew_still_remain' => '还差',
		'rew_receive_next_award' => '即可领取下一级奖励',
		'rew_red_packet' => '红包',
		'rew_sales_to_receive' => '销售额可领取',
		'rew_received' => '已领取',
		'rew_receive' => '领取',
		'rew_shortfall' => '未达标',
		'rew_sales_award_bonus' => '销售红包奖励',
		'rew_sales_total_amount' => '销量总金额每达到 （元）',
		'rew_sales_bonus_price' => '红包奖励金额',
		'rew_sales_accumulate_reward' => '销售累积奖励',
		//pc add
		'rew_monthly_sales' => '本月销售额',
		'rew_amount' => '奖励金额',
		'rew_time' => '奖励时间',
		'rew_standard_time' => '达标时间',
		'rew_red_envelopes' => '发红包',

		/////////////////
		//	Message    //
		/////////////////
		'msg_notify' => '通知',
		'msg_notify_detail' => '通知详情',
		//pc add
		'msg_order_quantity' => '订单数量',
		
		/////////////////
		//	Log    //
		/////////////////
		'l_system' => '系统日志',
		'l_operation_type' => '操作类型',
		'l_operator' => '操作者',
		'l_affiliation' => '所属机构',
		'l_operating_time' => '操作时间',
		'l_ip' => '访问IP',
		'l_system' => '所属系统',
		'l_module_name' => '模块名称',
		'l_operation_content' => '操作内容',
		
		/////////////////
		//	Setting    //
		/////////////////
		'set_inventory_reminder' => '库存提醒',
		'set_inventory_is_low' => '库存不足时提醒',
		'set_stock_is_low' => '库存不足时候预警数量',
		'set_inventory_fail' => '库存即将失效时提醒',
		'set_inventory_warning_time' => '库存即将失效时预警时间',
		'set_allow_warning_product' => '允产品组合进货',
		'set_order_service_card' => '订单服务卡有效期',
		'set_single_product' => '单产品进货最大数量',
		'set_total_amount' => '销量总金额超过此数值奖励',
		'set_sales_cross' => '销售额跨月累计',

		'str_no_data' => '显示数据无!',
		'input_valid_num' => '输入有效数字!',
		//activation
		'ac_phy_card_title' => '物理卡激活',
		'ac_vir_card_title' => '虚拟卡激活',
		'ac_card_exist_title' => '卡不存在。',
		'ac_card_avtivated_title' => '卡片已经激活了。',
		'rt_card_registered_title' => '这张卡已经被注册。',
		'rt_machinecode_no_title' => '这台机器代码不存在。',
		
		'send_mail_updatetime' => '更新时间',
	];
	
	
	$en = [
		////////////////////
		// Global message //
		////////////////////
			//category
		'home_title' => 'DELL Service Card System',
		'home_title_m' => 'DELL Service Card',
		'label_overview' => 'Overview',
		'label_product' => 'Products',
		'label_order' => 'Order',
		'label_sale' => 'Sales',
		'label_stock' => 'Stock',
		'label_statistic' => 'Statistic',
		
		'label_generate' => 'Generate',
		'label_reward' => 'Rewards',
		'label_sale_amount' => 'Sales AMT.',
		'label_staff' => 'Staff Information',
		'label_user' => 'Users',
		'label_client' => 'Clients',
		'label_person' => 'persons',
		'label_dealer' => 'Dealers',
		'label_message' => 'Messages',
		
		'label_added' => 'Added',
		'label_total' => 'Total',
		'label_cn_cunit' => '‎¥',
		'label_card_unit' => 'cards',
		//pc add
		'label_log' => 'Log',
		'label_back' => 'Back',
		
			// date & time
		'day' => 'Day',
		'qr_code' => 'QR Code',
		'days' => ' days',
		'week' => 'Week',
		'month' => 'Month',
		'season' => 'Season',
		'year' => 'Year',
		'years' => 'Years',
		'day_short' => 'D',
		'week_short' => 'W',
		'month_short' => 'M',
		'season_short' => 'S',
		'year_short' => 'Y',
		'start date' => 'Start date',
		'end date' => 'End date',
		'start day' => 'Start day',
		'end day' => 'End day',
		'forever_valid_time' => 'Forever',
		'new' => 'new',
		
			// number
		'number_0' => '0',
		'number_1' => '1',
		'number_2' => '2',
		'number_3' => '3',
		'number_4' => '4',
		'number_5' => '5',
		'number_6' => '6',
		'number_7' => '7',
		'number_8' => '8',
		'number_9' => '9',

        // number sequence
        'admin_level_dealer' => 'DELL Company',
        '1st_level_dealer' => '1st level dealer',
        '2nd_level_dealer' => '2nd level dealer',
        '3rd_level_dealer' => '3rd level dealer',
        '4th_level_dealer' => '4th level dealer',
        '5th_level_dealer' => '5th level dealer',
        '6th_level_dealer' => '6th level dealer',
        '7th_level_dealer' => '7th level dealer',
        '8th_level_dealer' => '8th level dealer',
        '9th_level_dealer' => '9th level dealer',
        '10th_level_dealer' => '10th level dealer',
        '11th_level_dealer' => '11th level dealer',
        '12th_level_dealer' => '12th level dealer',
        '13th_level_dealer' => '13th level dealer',
        '14th_level_dealer' => '14th level dealer',
        '15th_level_dealer' => '15th level dealer',
        '16th_level_dealer' => '16th level dealer',
        '17th_level_dealer' => '17th level dealer',
        '18th_level_dealer' => '18th level dealer',
        '19th_level_dealer' => '19th level dealer',
        '20th_level_dealer' => '20th level dealer',

        // general
		'physical_card_code' => 'Card code',
		'selected_physical_card' => 'Selected physical cards',
		'selected_pcard_quantity' => 'Selected quantity',
		'toselect_pcard_quantity' => 'Quantity to select',
		'valid_pcard_code' => 'Valide card code',
		'valid_pcard_code_s' => 'Valid',
		'invalid_pcard_code' => 'Invalide card code',
		'card_code_s' => 'Card code ',
		'import' => 'Import',
		'template_file' => 'Template',
		'template_sample' => 'Sample',
		'error_input_data_incorrect' => 'Input values is incorrect.',
		'error_input_data_duplicate' => 'Input values is duplicated.',
		'error_file_upload_failed' => 'File uploads failed.',
		'error_no_valid_card' => 'There is no valid card',
		'login' => 'Login',
		'field_required' => 'Insert correct value',
		'field_required_s' => 'Required',
		'select' => 'Select',
		'setting' => 'Setting',
		'submit' => 'Submit',
		'purchase' => 'Purchase',
		'search' => 'Search',
		'note' => 'Note',
		'all' => ' All ',
		'all city' => 'All cities',
		'unit price' => 'Unit Price',
		'quantity' => 'Quantity',
		'discount' => 'Discount',
		'purchase date' => 'Purchase Date',
		'seller' => 'Seller',
		'revenue' => 'Revenue',
		'register' => 'Register',
		'register_short' => 'Reg',
		'service card' => 'Sevice Card ',
		'service card_short' => 'Card ',
		'activation' => 'Activation',
		'activation_short' => 'ACT',
		'number' => 'Number',
		'id' => 'ID',
		'password' => 'Password',
		'password_short' => 'PWD',
		'valid period' => 'Valid period',
		'client' => 'Client',
		'name' => 'Name ',
		'phone' => 'Phone ',
		'clientname' => 'Client Name',
		'contact' => 'Contact',
		'download_all' => 'All Download',
		'download' => 'Download',
		'download_short' => 'Down',
		'return' => 'Return',
		'email' => 'Email',
		'email_short' => 'Email',
		'sales represent' => 'Sales Agent',
		'di' => '',
		'tiao' => '',
		'total' => 'Total',
		'no' => 'No.',
		'code' => 'Code',
		'define_name' => 'Name',
		'complete' => 'Complete ',
		'cancel' => 'Cancel',
		'custom' => 'Custom',
		'synchronize' => 'Synchronize',
		'synchronize_m' => 'Sync.',
		'type' => 'Type',
		'state' => 'State',
		'introduce' => 'Introduce',
		'introduce_m' => 'Intro.',
		'activate_card' => 'Activate card',
		'promotion' => 'Promotion',
		'promotion_m' => 'Promo',
		'card_no' => 'Card No.',
		'scan' => 'Scan',
		'add' => 'Add',
		'ten_pro' => '0%',
		'remain' => 'Remain ',
		'not_have' => 'nothing',
		'all_select' => 'Select all',
		'confirm' => 'Confirm',
		'use_on' => 'On',
		'use_off' => 'Off',
		'rule' => 'Rule',
		'income' => 'Income',
		//pc add
		'prompt' => 'prompt',
		'modify' => 'Modify',
		'no_data' => 'There is no data.\nPlease check again!',
		'item_count' => '',
		'others' => 'others ',
		'delete_selected' => 'Delete selected',
		'short_purchase' => 'Purc.',
		'short_return' => 'Ret.',
		'cost_price' => 'Cost price',
		'now_loading' => 'Loading',
		'select_dealer' => 'Select Dealer',
		'order_approved' => 'Approved',
		'order_unapproved' => 'Unapproved',
		'save_dlg_message_fail' => 'Saved failed, Please try again!',
		'send_dlg_title' => 'Send successfully',
		'send_dlg_title_fail' => 'Sending failed',
		'send_dlg_message_fail' => 'Sending failed, Please try again!',
		'import_dlg_title' => 'Import successfully',
		'import_dlg_message' => 'Import data file successfully。',
		'import_dlg_title_fail' => 'Import failed',
		'import_dlg_message_fail' => 'Import data file failed',
		'del_confirm_title' => 'Confirm before delete',
		'del_confirm_message' => 'Will you delete selected items?<br>Can not recover items after delete',
		'select_confirm_title' => 'No selected items',
		'select_confirm_message' => 'Plseae select one or more items',
		'newmsg_confirm_title' => 'New message',
		'newmsg_confirm_message' => ' new messages arrived. Please check new message',
		'card_generate' => 'Gen. Cards',
		'go_msg_page' => 'Message page',
		'info' => 'Info',
		'address' => 'Address',
		'dingding_account' => 'Dingtalk',
		'corporation' => 'Company',
		'level' => 'Level',
		'position' => 'Position',
		'my_account' => 'My Account',
		'my_company' => 'My Dealer',
		'my_account_l' => 'My Account',
		'my_up_dealer' => 'Higher Dealer',
        'unit_price' => 'Unit Cost',

		// Error
		'err_no_permission' => 'You do not have the appropriate authority!',
		'please_select' => 'Please select one item',
		'no_corresponding_data' => 'There is no corresponding data!',
		'no_permission_edit' => 'No permission to modify this data!',
		'err_save_fail' => 'Saving failed. Please contact administrator！',
		'password_setting' => 'Paasword Setting',
		'password_length' => 'Password Length',
		
		//////////////////
		//   overview   //
		//////////////////
		'ov_period_lavel' => 'Data overview of this :preriod_time',
		'ov_period_card' => 'Service cards of this :preriod_time',
		'ov_client_cards' => 'Client',
		'ov_sale_cards' => 'Sale',
		'ov_stock_cards' => 'Stock',
		'ov_soon_expire' => 'Soon Expire',
		'ov_soon_expire_m' => 'Soon EXP',
		'ov_expired' => 'Expired',
		'ov_activation' => 'Activation',
		'ov_register' => 'Register',
		'ov_manage_machine_code' => 'Manage M/C code',
		'ov_card_business' => 'Service card business',
		'ov_manage_card' => 'Service card management',
		'ov_manage_sales' => 'Sales management',
		'ov_today_data' => 'Today`s data',
		'ov_search_card_data' => 'Search card data',
		'import_machine_code_m' => 'Import Dell M/C code',
		'list_machine_code_m' => 'Dell M/C code',
		'success_machine_code_m' => 'Dell M/C code register success',
		'exist_machine_code_m' => 'Dell M/C code already exists',
		'fail_machine_code_m' => 'Dell M/C code register fail',
		'scan_machine_code_m' => 'Scan Dell M/C code',
		'ov_period_week_m' => 'Week',
		'ov_period_month_m' => 'Month',
		'ov_period_season_m' => 'Quater',
		'current_month_m' => 'This Month',
		'time_quater' => 'Season',
		'ov_period_year_m' => 'Year',
		'one_year_m' => 'One year',
		'ov_period_custom_m' => 'Custom',
		'ov_yesterday_gold_sale' => 'Yesterday best seller',
		//pc add
		'ov_one_year_products' => 'Ling Yue warranty for one year products',
		'ov_one_year_services' => 'DELL one year on-site service',
		'ov_product_code' => 'Product code',
		'ov_sales_store' => 'Sales store',
		'ov_status' => 'Status',
		'ov_details' => 'Details',
		'ov_machine_code_management' => 'Machine code management',
		'ov_batch_deletion' => 'Batch deletion',
		'ov_batch_import' => 'Batch import',
		'ov_machine_code_number' => 'Machine code number',
		'ov_import_time' => 'Import time',
		'ov_bulk_import_machine_code' => 'Bulk import machine code',
		'ov_select_the_import_file' => 'Select the import file',
		'ov_alarm_msg' =>'Import the file, please fill in the template format,<br> click <a class="fontcolorblue" href="./contents/import/machine_code/sample/machine_code_sample.csv">here</a> to download the template.',
		'ov_import' => 'Import',
		'service_type' => 'sevice Type',
		
		//////////////////
		//    product   //
		//////////////////
		'pr_label' => 'Products',
		'pr_edit_m' => 'Prod. edit',
		'pr_add_m' => 'Prod. add',
		'pr_info' => 'Information',
		'pr_item_manage' => 'Manage',
		'pr_item_add' => 'Prod. Add',
		'pr_item_all' => 'All Prod.',
		'pr_item_no' => 'Prod. No.',
		'pr_item_name' => 'Name',
		'pr_item_kind' => 'Kind',
		'pr_item_price' => 'Price',
		'pr_order_limit' => 'Order limit',
		'pr_promotion_price' => 'Promo Price',
		'pr_item_status' => 'Status',
		'pr_item_description' => 'Description',
		'pr_item_stock' => 'Stock',
		'pr_item_edit' => 'Edit',
		'pr_item_save' => 'Save',
		'pr_item_delete' => 'delete',
		'pr_item_cancel' => 'cancel',
		'pr_item_select_m' => 'Select Prod.',
		'pr_type_manage_title' => 'Manage Type',
		'pr_type_manage' => '+Manage Type',
		'pr_type_add' => '+Add type',
		'pr_standard_price' => 'Standard price',
		'pr_standard_price_m' => 'S. Price',
		'pr_standard_price_s' => 'S. Price',
		'pr_enter_card_password' => 'Please enter card No. and password',
		'pr_notify_no_price' => 'You haven`t set price yet',
		'pr_notify_set_price?' => 'Would you like to set the price of the product now?',
		'pr_set_price' => 'Set now',
		'pr_not_now' => 'Not now',
		'pr_enter_type_name' => 'Enter product type name',
        'pr_catalog_level' => 'Catalog Level',
        'pr_catalog_name' => 'Catalog Name',
        'pr_update_date' => 'Update Date',

        //pc add
		'pr_list' => 'Product List',
		'pr_all_categories' => 'All product categories',
		'pr_conventional' => 'Conventional products',
		'pr_unconventional' => 'Unconventional products',
		'pr_non-national' => 'Non-national products',
		'pr_level2_classification' => 'Level 2 product classification',
		'pr_class1_classification' => 'Class 1 type',
		'pr_class2_classification' => 'Class 2 type',
		'pr_class3_classification' => 'Custom type',
		'pr_class1_classification_s' => 'Class 1',
		'pr_class2_classification_s' => 'Class 2',
		'pr_class3_classification_s' => 'Custom',
		'pr_view' => 'View',
		'pr_return' => 'Return',
		'pr_service_card_information' => 'Service card information',
		'pr_service_card_cover' => 'Service card cover',
		'pr_description' => 'product description',
		'pr_extension_card' => 'Extension card',
		'pr_home_repair_card' => 'Home repair card',
		'pr_edit_save_msg' => 'Service card product "{?product.name?}" succefully saved!<br>Not set the price, to set up?',
		'pr_setting_price' => 'Setting price',
		'pr_not_set_yet' => 'Not set up yet',
		'pr_classification_management' => 'Product classification management',
		'pr_type_level' => 'Class level',
		'pr_name' => 'Product name',
		'pr_active_status_desciption' => 'The card activation succeed.',
		'pr_active_continue' => 'Continue',
		'pr_no_card' => 'No Card',
		'pr_register_fail' => 'Register Fail!!!',
		'upload card logo image' => 'Upload card logo image',
		'pr_save_dlg_title' => 'Save success',
		'pr_save_dlg_message' => ' product saved successfully',
		'pr_save_dlg_title_fail' => 'Save failed',
		'pr_save_dlg_message_fail' => ' product save failed, Please try again!',
		'pr_save_dlg_message_exist' => 'This product name exists already.',
		
		//////////////////
		//     order    //
		//////////////////
		'od_info' => 'Order Information',
		'od_setting' => 'Order setting',
		'od_detail' => 'Order details',
		'od_start_order' => 'Ordering',
		'od_order_all' => 'All',
		'od_order_sales' => 'Saled',
		'od_order_ship' => 'Shipped',
		'od_order_return' => 'Returned',
		'od_cards_all' => 'All cards',
		'od_dealers_all' => 'All dealers',
		'od_type_price' => 'Dis/Ori',
		'od_order_quantity' => 'Quantity',
		'od_order_date' => 'Order Date',
		'od_order_settled' => 'Setteled',		
		'od_order_type' => 'Order type',
		'od_prod_select' => 'Prod. Selection',
		'od_discount_price' => 'DIS',
		'od_original_price' => 'Orig',
		'od_quantity' => 'Quantity',
		'od_remain_stock' => 'Remain',
		'od_alert_lessthan' => 'You must order this type more than ',
		'od_order_now' => 'Order now!',
		'od_order_pending' => 'Pending',
		'od_order_sold' => 'Sold',
		'od_order_returned' => 'Returned',
		'od_order_no' => 'Order No.',
		'od_order_confirm' => 'Order confirm',
		'od_agree_purchase' => 'Agree purchase',
		'od_agree_return' => 'Agree return',
		'od_purchase_total2' => 'Purchase order total',
		'od_return_total2' => 'Return order total',
		'od_is_it_correct' => 'Correct?',
		'od_allow_multiple_purchase' => 'Allow multiple products purchase',
		'od_minval_single_purchase' => 'Minimum quantity of single product purchase (cards)',
		//pc add
		'od_search_name' => 'name or code search',
		'od_export' => 'Export',
		'od_import' => 'Import',
		'od_product' => 'Order product',
		'od_status' => 'Order Status',
		'od_effective_time' => 'Order effective time',
		'od_return_success_time' => 'Return success time',
		'od_number' => 'Order number',
		'od_effective_time1' => 'Effective time',
		'od_purchase_total' => 'Purchase total',
		'od_total_price' => 'Total price',
		'od_myorder' => 'My order',
		'od_export_title' => 'Export Order',
		'od_import_title' => 'Import Order',
		'od_import_msg' => 'Import the file, please fill in the template format',
		'od_export_msg' => 'Enter email to send.',
		'od_purchased' => 'Purchased',
		'od_agree_status' => 'Agree status',
		'od_agree' => 'Agree',
		'od_disagree' => 'Disagree',
		'od_refusal' => 'Refusal',
		'od_pcard_import_result' => 'File import result',
		'od_pcard_valid_cards' => 'Valid cards',
		'od_pcard_invalid_cards' => 'Invalid cards',
		'od_pcard_invalid_cards_list' => 'Invalid card list',
		'od_pcard_quantity_lack' => 'The number of physical cards selected is not enough.',
		'od_pcard_quantity_return_lack' => 'The physical card list to return is not accurate.',
		
		//////////////////
		//    sales     //
		//////////////////
		'sl_info' => 'Sales Information',
		'sl_card_active' => 'S. Card ACT',
		'sl_unregistered' => 'Unregistered',
		'sl_registered' => 'Registered',
		'sl_unlimited' => 'Unlimited',
		'sl_servicecard_number_search' => 'Sevice Card Number',
		'sl_seller' => 'Seller',
		'sl_card_product' => 'Card Product',
		'sl_continue_register' => 'User Reg',
		'sl_notyet_register' => 'Not yet Reg',
		'sl_binding_card' => 'Binding Card',
		'sl_machine_code' => 'Code',
		'sl_after_sale' => 'After Sale',
		'sl_user_register' => 'User Reg',
		'sl_register_ranking' => 'Products',
		'sl_income_ranking' => 'Income',
		'sl_dealer_ranking' => 'Dealer',
		'sl_seller_ranking' => 'Seller',
		'sl_my_sale_amount' => 'Sale AMT',
		'sl_total_sale_amount' => 'Total Sale',
		'sl_my_income' => 'Income',
		'sl_sales_total' => 'Sales total',
		//pc add
		'sl_product_category' => 'Product Category',
		'sl_expired' => 'Expired',
		'sl_highest_sales' => 'Highest sales',
		'sl_dealer_name' => 'Dealer name',
		'sl_selling_best' => 'Selling the best products',
		'sl_salesperson_name' => 'Salesperson name',
		'sl_owned_stores' => 'Owned stores',
		'sl_volume' => 'Sales volume',
		
		//////////////////
		//    stock     //
		//////////////////
		'st_info' => 'Stock Information',
		'st_setting' => 'Stock setting',
		'st_cardname_search' => 'Service Card Product Name',
		'st_purchase_retail' => 'Purchase/Retail',
		'st_purchase_channel' => 'Channel',
		'st_servicecard_operation' => 'Operation',
		'st_emailsend_note' => 'Activation code will be sent to your email',
		'st_download_servicecard' => 'Download',
		'st_return_servicecard' => 'Return Service Card',
		'st_return_cardname' => 'Card Name',
		'st_return_count' => 'Count',
		'st_return_count_available' => 'Available return count',
		'st_want_exchange' => 'Exchange',
		'st_item_exchange' => 'Exchange Product',
		'st_item_stocknote' => 'Current stock',
		'st_submit_application' => 'Submit',
		'st_insufficient_stock' => 'Insufficient',
		'st_soon_disable' => 'Soon disable',
		'st_enter_email' => 'Please enter email address',
		'st_purchase_price' => 'Purchase',
		'st_purchase_soon' => 'Purchase now ',
		'st_return_availabe' => 'Available',
		'st_return_request' => 'Request return',
		'st_purchase_notify' => 'Purchase now, Total:',
		'st_return_notify' => 'Now request return，Total:',
		'st_stock_shortage_warning' => 'Stock shortage warning',
		'st_stock_shortage_warning_count' => 'Shortage warning counts',
		'st_stock_expire_warning' => 'Stock soon disable warning',
		'st_stock_expire_warning_count' => 'Soon disable warning days',
		'st_countdown_after_agree' => 'Count down after agree',
		//pc add
		'st_search' => 'search word',
		'st_dealer_search' => 'dealer name...',
		'st_user_search' => 'user name...',
		'st_physical_card' => 'Physical card',
		'st_virtual_card' => 'Virtual card',
		'st_usabled' => 'Usabled',
		'st_service_card_information_details' => 'Service card information details',
		'st_product_type' => 'Product type',
		'st_machine_code' => 'Machine code',
		'st_machine_code_s' => 'M.Code',
		'st_customer_information' => 'Customer Information',
		'st_username' => 'Username',
		'st_notyet_actived' => 'None',
		'st_already_actived' => 'Actived',
		'st_already_saled' => 'Saled',
		'st_already_expired' => 'Expired',
		'st_mail_send_message' => 'Send stock information successfully to {?sendemail?}. Please check your email inbox!',
		'st_download_title' => 'Stock Info download',
		'st_download_toemail' => 'To Email',
		'st_download_tofile' => 'To File',
		
		//////////////////
		//  Statistics  //
		//////////////////
		'sta_info' => 'Statistics Information',
		'sta_sort_sales' => 'Sort by sales',
		'sta_sort_purchase' => 'Sort by purchase',
		'sta_sort_shipped' => 'Sort by shipment',
		'sta_dealer_name' => 'Agent Name',
		'sta_purchase_order' => 'Purchase',
		'sta_shipment_order' => 'Shipment',
		'sta_return_order' => 'Returned',
		'sta_terminal_order' => 'Terminal',
		'sta_sale_agentname' => 'Sell Agency',
		'sta_sale_amount' => 'Quantity',
		'sta_sale_price' => 'Price',
		'sta_bonus_price' => 'Bonus',
		'sta_bonus_status' => 'Status',
		'sta_sale_point' => 'Point',
		'sta_bonus_send' => 'Send bonus',
		
		//////////////////
		//     User     //
		//////////////////
		'u_info' => 'User Information',
		'u_terminal_user' => 'Termianl',
		'u_username_search' => 'Search user name',
		'u_user_name' => 'User Name',
		'u_buy_product' => 'Buyed Product',
		'u_dealer_channel' => 'Channel',
		'u_servicecard_id' => 'Card Id',
		'u_servicecard_pass' => 'Card Password',
		'expire_date' => 'Expire',
		'person_charge' => 'Director',
		'u_office_address' => 'Agent Addr',
		'u_office_level' => 'Agent Level',
		'u_customer_type' => 'Customer Type',
		'u_dealer_code' => 'Dealer Code',
		'u_reg_time' => 'Reg Date',
		'u_dealer_info' => 'Dealer_info',
		'u_none_reward' => 'None reward',
		'u_give_reward' => 'Gived reward',
		'u_sales_shortfall' => 'Shortfall',
		'u_import_userdata' => 'Import marketing staffs` data from Dingtalk',
		'u_btn_import' => 'Import',
		'u_import_dealerdata' => 'Import dealerpoint data from Dingtalk',
		'u_outstanding_price' => 'Outstanding',
		'u_settled_month' => 'Settled this month',
		'u_item_stock' => 'Prod. stock',
		'u_activation_count' => 'ACT count',
		'u_register_count' => 'REG count',
		'u_total_sales' => 'Total sales',
		'u_cur_month_sales' => 'This month',
		'u_outstanding_order' => 'Outstanding order',
		'u_outstanding_writeoff' => 'Write off the outstanding amount ',
		//pc add
		'u_retail_stores' => 'Retail stores',
		'u_import' => 'Import the dealer information',
		'u_monthly_settlement_amount' => 'Monthly settlement amount',
		'u_unsettlement' => 'Unsettlement',
		'u_settled' => 'Settled',
		'u_customer_type' => 'Customer type',
		'u_area' => 'Belongs to the area',
		'u_contact_address' => 'Ccontact address',
		'u_bindsigned' => 'Bindsigned',
		'u_product_activation' => 'Product activation',
		'u_product_registration' => 'Product registration',
		'u_confirm' => 'Confirm that it has been settled',
		'u_level' => 'User level',
		'u_district' => 'District',
		'u_bonus' => 'Bonus',
		
		//////////////////
		//    message     //
		//////////////////
		'ms_info' => 'Message Information',
		'ms_label_all' => 'All',
		'ms_label_notification' => 'Notification',
		'ms_label_inspection' => 'Inspection',
		'ms_search_keyword' => 'Please insert keyword',
		'ms_delete_message' => 'Delete',
		'ms_message_type' => 'Type',
		'ms_message_content' => 'Content',
		'ms_message_operation' => 'Operation',
		'ms_details' => 'Details',
		'ms_message_time' => 'Arrive Time',
		'ms_purchase_application' => 'Purchase',
		'ms_purchase_agree' => 'Agree',
		'ms_refuse_application' => 'Refuse',
		'ms_oder_prefix_notification' => 'Your order is in effect',
		'ms_oder_surfix_notification' => ' have been in stock',
		'Close' => 'Close',
		'close' => ' close',
		'ms_seller_new_prefix' => 'You have ',
		'ms_seller_new_suffix' => ' new messages, please check it',
		'ms_tab_system' => 'System',
		'ms_tab_audit' => 'Audit',
		'ms_tab_order' => 'Order',
		
		//////////////////
		//    Price     //
		//////////////////
		'price_label' => 'Price',
		'price_pricing' => 'Pricing',
		'price_promotion' => 'Promotion',
		'price_promotion_text' => 'Promotion',
		'price_change_price' => 'Price',
		'price_discount_price' => 'Discount',
		'price_discount_product' => 'Select Discount Product',
		'price_promotion_period' => 'Promotion valid',
		'price_purchase_price' => 'Purchase price',
		'price_shipment_price' => 'Shipment price',
		'price_wholesale_price' => 'Wholesale price',
		'price_store_price' => 'Store price',
		'price_purchase_our' => 'Purchase price',
		'price_current_selected' => 'Selected ',
		'price_item_unit' => ' products',
		'price_set_discount' => 'Discount',
		'price_selected_items' => 'Selected items',
		//pc add
        'label_table_image' => 'Image',
        'label_table_action' => 'Action',
		'price_retail_price' => 'Retail price',
		'price_promotional_discount' => 'Promotional discount',
		'price_batch_setting' => 'Batch setting',
		'price_promotion_time' => 'Promotion time',
		'price_promotional_outlets' => 'Promotional outlets',
		'price_selected_products' => 'Selected products',
		'price_custom_settings' => 'Custom settings',
		'price_discount_rate' => 'Rate',
		'price_admin_dealer' => 'DELL Company',
		'price_actual_price' => 'Actual price',
		'price_change_price' => 'Change',
		'price_total_promotion' => 'Total discount',
		'price_level_dealer' => 'level dealer',
		'price_success' => 'success',
		'price_save_fail' => 'Faile to save!',
		'price_base' => 'base price',
		'price_order_limit' => 'order limit',
		'price_seller' => 'seller',
		'price_sell' => 'sell price',
		'price_set_confirm' => 'Do you confirm price?',
		'price_btn_confirm' => 'Confirm',
		'price_btn_cancel' => 'Cancel',
		'price_set_low_alert' => '“Wholesale price cannot be lower than purchase price.” Do you want to continue?',
		'price_btn_continue' => 'Continue',
		'price_sending' => 'Sending...',
		'price_save_success' => 'Success save!',
		
		//////////////////
		//    Register  //
		//////////////////
		'rg_already_act' => 'Actived Prod.',
		'rg_regiset_dell_machine_code' => 'Register binding DELL machine code',
		'rg_scane_m_code' => 'Scan machine code',
		'rg_submit' => 'Register',
		'rg_success_register' => 'Successfully registered!',
		'rg_success_save' => 'Successfully saved!',
		'rg_success_refused' => 'Successfully refused!',
		'rg_fail_save' => 'Saving is failed!',
		'rg_fail_refus' => 'Refusing is failed!',
		'rg_error_save' => 'There is no registered machine code.',
		'rg_sale_price' => 'Sale Price',
		'rg_invalid_number' => 'Invalid number',
		'rg_invalid_pass' => 'The passwords do not match.',
		
		//////////////////
		//    Generate  //
		//////////////////
		'gen_select_card' => 'Select card',
		'gen_generate_card_short' => 'Generate',
		'gen_generate_card' => 'Generate card',
		'gen_card_no_example' => 'Card No example',
		'gen_card_part_id' => 'Product ID',
		'gen_card_part_area' => 'Area ID',
		'gen_card_part_random' => 'Random',
		'gen_pwd_example' => 'Password example',
		'gen_btn_generate' => 'Generate',
		'gen_msg_generate' => 'Now generating cards',
		'gen_physical_card_inventory' => 'Physical cards',
		'gen_virtual_card_inventory' => 'Virtual cards',
		'gen_dealer_inventory' => 'Dealer cards',
		'gen_service_card_name' => 'Service card name',
		'gen_service_card_code' => 'Service card code',
		'gen_service_card_expiry_date' => 'Service card expiry date',
		'gen_select_the_service_card_type' => 'Select the service card type',
		'gen_mcard_type' => 'Card type',
		'gen_enter_service_cards' => 'Enter the number of service cards',
		'gen_service_card_rules' => 'Generate service card rules',
		'gen_check_generate' => 'Confirm card creation',
		'gen_check_next' => 'have been created.',
		'gen_check_cardcount' => 'Card creation exceeded.',
		'gen_invalid_number10000' => 'The number value is between 1 and 10000.',
		
		//////////////////
		//    Purchase  //
		//////////////////
		'pur_purchase_price' => 'Purchase',
		'pur_bulk' => 'Bulk purchase',
		'pur_operating' => 'operating',
		'pur_price' => 'Purchase price',
		'pur_btn_msg' => 'A total of 600,000 yuan, submitted to the purchase order',
		'pur_btn_msg_prev' => 'A total of',
		'pur_btn_msg_next' => '¥, submitted to the purchase order',
		'pur_check_addtitle' => 'Purchase Order',
		'pur_check_add_next' => 'have been purchased.',
		'pur_check_return_next' => 'have been returned.',
		'pur_check_success' => 'The operation was successful.',
		'pur_is_price' => 'The price of product does not exist.',
		'pur_warning' => 'Price setting warning!!!',
		'pur_invalid_prev1' => 'The number value is between ',
		'pur_invalid_prev2' => ' and ',
		'pur_invalid_prev3' => '',
		'pur_continue_work' => 'Do you want to continue?',
		
		
		//////////////////
		//    Reward    //
		//////////////////
		'rew_reward_setting' => 'Reward setting',
		'rew_reward_setting_btn' => '+Setting',
		'rew_reward_unissued' => 'Unissued',
		'rew_reward_issued' => 'Issued',
		'rew_sales_bonus' => 'Sales bonus',
		'rew_agree_bonus?' => 'Agree bonus？',
		'rew_still_remain' => 'Still ',
		'rew_receive_next_award' => 'to receive the next Award',
		'rew_red_packet' => 'Red packet ',
		'rew_sales_to_receive' => ' sales to receive',
		'rew_received' => 'Received',
		'rew_receive' => 'Receive',
		'rew_shortfall' => 'Shortfall',
		'rew_sales_award_bonus' => 'Sales award bonus',
		'rew_sales_total_amount' => 'Sales total amount （元）',
		'rew_sales_bonus_price' => 'Bonus price',
		'rew_sales_accumulate_reward' => 'Accumulated reward',
		//pc add
		'rew_monthly_sales' => 'Monthly sales',
		'rew_amount' => 'Reward amount',
		'rew_time' => 'Reward time',
		'rew_standard_time' => 'Standard time',
		'rew_red_envelopes' => 'Red envelopes',

		/////////////////
		//	Message    //
		/////////////////
		'msg_notify' => 'Notification',
		'msg_notify_detail' => 'Detail',
		//pc add
		'msg_order_quantity' => 'quantity of order',
		
		/////////////////
		//	Log    //
		/////////////////
		'l_system' => 'System log',
		'l_operation_type' => 'Type of operation',
		'l_operator' => 'Operator',
		'l_affiliation' => 'Affiliation',
		'l_operating_time' => 'Operating time',
		'l_ip' => 'Access IP',
		'l_system' => 'System',
		'l_module_name' => 'Module name',
		'l_operation_content' => 'Operation content',
		
		/////////////////
		//	Setting    //
		/////////////////
		'set_inventory_reminder' => 'Inventory reminder',
		'set_inventory_is_low' => 'Reminders when inventory is low',
		'set_stock_is_low' => 'When the stock is low, the number of warnings',
		'set_inventory_fail' => 'Reminders when inventory is about to fail',
		'set_inventory_warning_time' => 'Inventory is about to fail when the warning time',
		'set_allow_warning_product' => 'Allow the product portfolio to purchase',
		'set_order_service_card' => 'Order service card expiration date',
		'set_single_product' => 'Single product purchase the largest number',
		'set_total_amount' => 'The total amount of sales exceeds this value',
		'set_sales_cross' => 'Sales cross-monthly cumulative',
		
		'str_no_data' => 'No display data!',
		'input_valid_num' => 'Please input the valid number!',
		//activation
		'ac_phy_card_title' => 'Physical card Activation',
		'ac_vir_card_title' => 'Virtual card Activation',
		'ac_card_exist_title' => 'Card does not exist.',
		'ac_card_avtivated_title' => 'The card has already been activated.',
		'rt_card_registered_title' => 'The card has already been registered.',
		'rt_machinecode_no_title' => 'The machine code does not exist.',
		
		'send_mail_updatetime' => 'Update Time',
	];
	
	foreach($cn as $key => $item){
		if(!isset($en[$key])) echo $key."<br >";
	}
?>